# Generated by Django 3.2.9 on 2021-12-09 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snumber', models.CharField(max_length=10, null=True)),
                ('sname', models.CharField(max_length=20, null=True)),
                ('sdescription', models.TextField(max_length=100, null=True)),
                ('slocation', models.CharField(max_length=10, null=True)),
                ('sposition', models.CharField(max_length=10, null=True)),
                ('ssum', models.IntegerField(null=True)),
                ('sunit', models.CharField(max_length=5, null=True)),
                ('spackage', models.CharField(max_length=20, null=True)),
                ('sprovider', models.CharField(max_length=20, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
