# Generated by Django 3.2.9 on 2021-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='sdescription',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='slocation',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='sname',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='snumber',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='spackage',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='sposition',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='sprovider',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='ssum',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='sunit',
        ),
        migrations.AddField(
            model_name='storage',
            name='sArea',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='sCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='sDescription',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='sId',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='sName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='sPosition',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='sUnit',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='spartNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='ssafeCount',
            field=models.IntegerField(null=True),
        ),
    ]
