# Generated by Django 3.2.9 on 2021-12-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20211209_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('sId',)},
        ),
        migrations.RemoveField(
            model_name='storage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='updated',
        ),
    ]
