# Generated by Django 3.2.9 on 2021-12-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_lendstorage_idtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendstorage',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='lendstorage',
            name='idText',
        ),
        migrations.AddField(
            model_name='lendstorage',
            name='sName',
            field=models.CharField(max_length=20, null=True, verbose_name='借库名'),
        ),
    ]
