# Generated by Django 3.2.9 on 2021-12-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20211211_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendstorage',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='lendstorage',
            name='user',
        ),
    ]
