# Generated by Django 3.2.9 on 2021-12-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20211211_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendstorage',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to='storage.storage'),
        ),
    ]
