# Generated by Django 3.2.9 on 2021-12-11 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0010_lendstorage_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lendstorage',
            old_name='sid',
            new_name='storage',
        ),
        migrations.AddField(
            model_name='lendstorage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
