# Generated by Django 3.2.9 on 2021-12-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20211211_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendstorage',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='lendstorage',
            name='user',
        ),
    ]
