# Generated by Django 3.2.9 on 2021-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20211211_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendstorage',
            name='sName',
            field=models.TextField(null=True, verbose_name='借库名'),
        ),
    ]
