# Generated by Django 3.2.9 on 2021-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_auto_20211211_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='sName',
            field=models.CharField(max_length=20, null=True, verbose_name='品名'),
        ),
    ]
