# Generated by Django 3.2.9 on 2021-12-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_avatar_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendstorage',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages', to='storage.storage'),
        ),
    ]
