# Generated by Django 3.2.9 on 2021-12-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_lendstorage_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendstorage',
            name='storage',
        ),
        migrations.AddField(
            model_name='avatar',
            name='sArea',
            field=models.CharField(max_length=10, null=True, verbose_name='存放区域'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='sCount',
            field=models.IntegerField(null=True, verbose_name='库存余量'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='sDescription',
            field=models.TextField(max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='sId',
            field=models.CharField(max_length=10, null=True, verbose_name='库存品代码'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='sPosition',
            field=models.CharField(max_length=10, null=True, verbose_name='存放库位'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='sUnit',
            field=models.CharField(max_length=5, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='spartNumber',
            field=models.CharField(max_length=20, null=True, verbose_name='物料号'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='ssafeCount',
            field=models.IntegerField(null=True, verbose_name='安全库存'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
