# Generated by Django 3.2.9 on 2021-12-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0021_auto_20211206_2231'),
        ('storage', '0021_lendstorage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendstorage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='lendstorage',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to='storage.storage'),
        ),
    ]
