# Generated by Django 3.2.9 on 2021-12-11 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0021_auto_20211206_2231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0023_remove_lendstorage_sname'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lCount', models.IntegerField(default=0, verbose_name='数量')),
                ('created', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='日期')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_in', to='storage.storage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OutStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lCount', models.IntegerField(default=0, verbose_name='数量')),
                ('created', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='日期')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_out', to='productplan.productplan')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_out', to='storage.storage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_out', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='LendStorage',
        ),
    ]
