# Generated by Django 3.2.9 on 2021-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0024_auto_20211211_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instorage',
            options={'ordering': ('-created',), 'verbose_name_plural': '入库记录'},
        ),
        migrations.AlterModelOptions(
            name='outstorage',
            options={'ordering': ('-created',), 'verbose_name_plural': '出库记录'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('-updated',), 'verbose_name_plural': '库存表'},
        ),
        migrations.AddField(
            model_name='instorage',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='outstorage',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='storage',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
    ]
