# Generated by Django 3.2.9 on 2021-12-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0027_auto_20211211_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='spartNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='物料号'),
        ),
    ]
