# Generated by Django 3.2.9 on 2021-12-14 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0029_alter_storage_sdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='sId',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='库存品代码'),
        ),
    ]
