# Generated by Django 3.2.9 on 2022-01-08 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0030_auto_20211214_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instorage',
            options={'ordering': ('-updated',), 'verbose_name_plural': '入库记录'},
        ),
        migrations.AlterModelOptions(
            name='outstorage',
            options={'ordering': ('-updated',), 'verbose_name_plural': '出库记录'},
        ),
        migrations.AddField(
            model_name='instorage',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='outstorage',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='instorage',
            name='created',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='outstorage',
            name='created',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='日期'),
        ),
    ]
