# Generated by Django 3.2.9 on 2022-02-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0032_alter_storage_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
