# Generated by Django 3.2.9 on 2022-02-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0034_inoutstorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstorage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outstorage',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='outstorage',
            name='user',
        ),
        migrations.DeleteModel(
            name='InStorage',
        ),
        migrations.DeleteModel(
            name='OutStorage',
        ),
    ]
