# Generated by Django 3.2.9 on 2022-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0037_alter_inoutstorage_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutstorage',
            name='direction',
            field=models.CharField(choices=[('in', '入库'), ('out', '出库'), ('buy', '采购')], default='out', max_length=5, verbose_name='操作方向'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='sId',
            field=models.CharField(max_length=10, verbose_name='库存品代码'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='spartNumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='物料号'),
        ),
    ]
