# Generated by Django 3.2.9 on 2022-02-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='operator',
        ),
    ]
