# Generated by Django 3.2.9 on 2022-02-23 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_service_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-created',), 'verbose_name_plural': '维修记录'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated',
        ),
        migrations.AddField(
            model_name='service',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='service_pictures/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='问题描述'),
        ),
    ]
