# Generated by Django 3.2.9 on 2022-03-21 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0030_auto_20220210_1643'),
        ('Service', '0005_auto_20220223_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='results',
        ),
        migrations.AddField(
            model_name='service',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='service',
            name='style',
            field=models.CharField(choices=[('servicein', '保内维修'), ('serviceout', '保外维修'), ('production', '工艺改进')], default='servicein', max_length=10, verbose_name='报告类型'),
        ),
        migrations.AlterField(
            model_name='service',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='productplan.productplan', verbose_name='订单号'),
        ),
    ]
