# Generated by Django 3.2.9 on 2021-11-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0004_auto_20211122_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productplan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='productplan.category', verbose_name='订单类型'),
        ),
    ]
