# Generated by Django 3.2.9 on 2021-11-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0006_auto_20211122_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='productplan',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='status',
            name='enddays',
            field=models.DateField(null=True, verbose_name='交货时间'),
        ),
        migrations.AddField(
            model_name='status',
            name='remarks',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='status',
            name='startdays',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='下单时间'),
        ),
    ]
