# Generated by Django 3.2.9 on 2021-11-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0007_auto_20211122_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productplan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productplan',
            name='status',
        ),
        migrations.AddField(
            model_name='category',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='productplan.productplan', verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='status',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_status', to='productplan.productplan', verbose_name='订单状态'),
        ),
    ]
