# Generated by Django 3.2.9 on 2021-11-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0008_auto_20211122_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='status',
            name='customer',
        ),
        migrations.AddField(
            model_name='productplan',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='productplan.category', verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='productplan',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='productplan.status', verbose_name='客户名称'),
        ),
    ]
