# Generated by Django 3.2.9 on 2021-11-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0009_auto_20211123_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='enddays',
        ),
        migrations.RemoveField(
            model_name='status',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='status',
            name='startdays',
        ),
    ]
