# Generated by Django 3.2.9 on 2021-11-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0010_auto_20211123_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productplan',
            name='category',
            field=models.CharField(choices=[('std', '标准'), ('unstd', '非标')], default='std', max_length=5),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
