# Generated by Django 3.2.9 on 2021-11-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0011_auto_20211123_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productplan',
            name='category',
            field=models.CharField(choices=[('std', '标准'), ('unstd', '非标')], default='std', max_length=5, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='productplan',
            name='status',
            field=models.CharField(choices=[('process', '进行中'), ('finish', '已完成')], default='process', max_length=10, verbose_name='订单状态'),
        ),
    ]
