# Generated by Django 3.2.9 on 2021-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0012_auto_20211123_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAssemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10, verbose_name='订单号')),
                ('startday', models.DateField(auto_now_add=True, verbose_name='下单时间')),
                ('endday', models.DateField(verbose_name='交货时间')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('title', models.CharField(max_length=10, verbose_name='装配')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessElPrepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10, verbose_name='订单号')),
                ('startday', models.DateField(auto_now_add=True, verbose_name='下单时间')),
                ('endday', models.DateField(verbose_name='交货时间')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('title', models.CharField(max_length=10, verbose_name='电路板准备')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessMePrepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10, verbose_name='订单号')),
                ('startday', models.DateField(auto_now_add=True, verbose_name='下单时间')),
                ('endday', models.DateField(verbose_name='交货时间')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('title', models.CharField(max_length=10, verbose_name='机械件准备')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessScPrepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10, verbose_name='订单号')),
                ('startday', models.DateField(auto_now_add=True, verbose_name='下单时间')),
                ('endday', models.DateField(verbose_name='交货时间')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('title', models.CharField(max_length=10, verbose_name='干涉仪准备')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10, verbose_name='订单号')),
                ('startday', models.DateField(auto_now_add=True, verbose_name='下单时间')),
                ('endday', models.DateField(verbose_name='交货时间')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('title', models.CharField(max_length=10, verbose_name='测试')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
