# Generated by Django 3.2.9 on 2021-11-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0013_processassemble_processelprepare_processmeprepare_processscprepare_processtesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processassemble',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_as', to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processelprepare',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_el', to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processmeprepare',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_me', to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processscprepare',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_sc', to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processtesting',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_ts', to='productplan.productplan'),
        ),
    ]
