# Generated by Django 3.2.9 on 2021-11-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0014_auto_20211123_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processassemble',
            name='title',
        ),
        migrations.RemoveField(
            model_name='processelprepare',
            name='title',
        ),
        migrations.RemoveField(
            model_name='processmeprepare',
            name='title',
        ),
        migrations.RemoveField(
            model_name='processscprepare',
            name='title',
        ),
        migrations.RemoveField(
            model_name='processtesting',
            name='title',
        ),
        migrations.AddField(
            model_name='processassemble',
            name='status',
            field=models.CharField(choices=[('process', '进行中'), ('finish', '已完成')], default='process', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='processelprepare',
            name='status',
            field=models.CharField(choices=[('process', '进行中'), ('finish', '已完成')], default='process', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='processmeprepare',
            name='status',
            field=models.CharField(choices=[('process', '进行中'), ('finish', '已完成')], default='process', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='processscprepare',
            name='status',
            field=models.CharField(choices=[('process', '进行中'), ('finish', '已完成')], default='process', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='processtesting',
            name='status',
            field=models.CharField(choices=[('process', '进行中'), ('finish', '已完成')], default='process', max_length=10, verbose_name='订单状态'),
        ),
    ]
