# Generated by Django 3.2.9 on 2021-11-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0015_auto_20211123_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtesting',
            name='id',
        ),
        migrations.AlterField(
            model_name='processtesting',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_ts', serialize=False, to='productplan.productplan'),
        ),
    ]
