# Generated by Django 3.2.9 on 2021-11-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0016_auto_20211123_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processassemble',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processelprepare',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processmeprepare',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processscprepare',
            name='id',
        ),
        migrations.AlterField(
            model_name='processassemble',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_as', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processelprepare',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_el', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processmeprepare',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_me', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processscprepare',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_sc', serialize=False, to='productplan.productplan'),
        ),
    ]
