# Generated by Django 3.2.9 on 2021-11-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0017_auto_20211123_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processassemble',
            options={'verbose_name': '装配中'},
        ),
        migrations.AlterModelOptions(
            name='processelprepare',
            options={'verbose_name': '电路板准备'},
        ),
        migrations.AlterModelOptions(
            name='processmeprepare',
            options={'verbose_name': '机械件准备'},
        ),
        migrations.AlterModelOptions(
            name='processscprepare',
            options={'verbose_name': '干涉仪准备'},
        ),
        migrations.AlterModelOptions(
            name='processtesting',
            options={'verbose_name': '测试中'},
        ),
    ]
