# Generated by Django 3.2.9 on 2021-11-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0019_auto_20211123_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtesting',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_ts', serialize=False, to='productplan.productplan', verbose_name='订单号'),
        ),
    ]
