# Generated by Django 3.2.9 on 2021-12-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0020_alter_processtesting_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processassemble',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_as', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processelprepare',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_el', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processmeprepare',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_me', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processscprepare',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_sc', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processtesting',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products_ts', serialize=False, to='productplan.productplan', verbose_name='订单号'),
        ),
    ]
