# Generated by Django 3.2.9 on 2022-01-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0021_auto_20211206_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
