# Generated by Django 3.2.9 on 2022-01-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0022_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processassemble',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proas', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processelprepare',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proel', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processmeprepare',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prome', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processscprepare',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prosc', serialize=False, to='productplan.productplan'),
        ),
        migrations.AlterField(
            model_name='processtesting',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prots', serialize=False, to='productplan.productplan', verbose_name='订单号'),
        ),
    ]
