# Generated by Django 3.2.9 on 2022-01-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0025_auto_20220129_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processassemble',
            old_name='orderid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='processelprepare',
            old_name='orderid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='processmeprepare',
            old_name='orderid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='processscprepare',
            old_name='orderid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='processtesting',
            old_name='orderid',
            new_name='product',
        ),
    ]
