# Generated by Django 3.2.9 on 2022-01-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0026_auto_20220131_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processassemble',
            old_name='product',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='processelprepare',
            old_name='product',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='processmeprepare',
            old_name='product',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='processscprepare',
            old_name='product',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='processtesting',
            old_name='product',
            new_name='orderid',
        ),
    ]
