# Generated by Django 3.2.9 on 2022-02-07 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productplan', '0027_auto_20220131_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proitem', models.CharField(max_length=10, verbose_name='操作项目')),
                ('newcontent', models.CharField(max_length=10, verbose_name='新内容')),
                ('operateday', models.DateField(null=True, verbose_name='操作时间')),
                ('orderid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_history_orderid', to='productplan.productplan', verbose_name='订单号')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_history_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '订单历史',
            },
        ),
    ]
