# Generated by Django 3.2.9 on 2022-02-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0028_producthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history_orderid', to='productplan.productplan', verbose_name='订单号'),
        ),
    ]
