# Generated by Django 3.2.9 on 2022-04-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0031_auto_20220416_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processassemble',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processmeprepare',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processscprepare',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processtesting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producthistory',
            options={},
        ),
        migrations.AddField(
            model_name='processassemble',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processmeprepare',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processscprepare',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processtesting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
